services:
  mysql:
    image: 'mysql:8.0'
    container_name: orion_db
    environment:
      - 'MYSQL_DATABASE=OrionWMS'
      - 'MYSQL_USER=Enzo'
      - 'MYSQL_PASSWORD=En648213!'
      - 'MYSQL_ROOT_PASSWORD=root_pass'
    ports:
      - '3307:3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: